version: '3.8'

services:
  backend:
    image: ghcr.io/kaiquenascimentov4/callcenter:latest
    networks:
      - portainer
      
    # 👇 ADICIONE ESTA PARTE AQUI 👇
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
    # 👆 ======================= 👆

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        # HTTPS
        - "traefik.http.routers.callcenter.rule=Host(`api-call.v4companyamaral.com`)"
        - "traefik.http.routers.callcenter.entrypoints=websecure"
        - "traefik.http.routers.callcenter.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.callcenter.loadbalancer.server.port=3001"
        # HTTP → HTTPS redirect
        - "traefik.http.routers.callcenter-http.rule=Host(`api-call.v4companyamaral.com`)"
        - "traefik.http.routers.callcenter-http.entrypoints=web"
        - "traefik.http.middlewares.callcenter-https.redirectscheme.scheme=https"
        - "traefik.http.routers.callcenter-http.middlewares=callcenter-https"

networks:
  portainer:
    external: true
